version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app-advanced
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/node-db

volumes:
  mongo_data:
